auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('addListing', views.add_listing, name="newListing"),
    path('listing/<int:listing_id>', views.entry_bid, name="entryBid"),
    path('listing/<int:listing_id>/place_bid/', views.place_bid, name="placeBid"),
    path('listing/<int:listing_id>/end_bid/',views.end_bid, name="endBid"),
    path('watchList', views.watch_list, name='watchList'),
    path('listing/<int:listing_id>/toggleWatch',views.toggle_watch_list, name='toggleWatch'),
    path('listing/<int:listing_id>/comment',views.add_comment, name='comment'),
    path('listing/<int:listing_id>/<int:comment_id>/editComment', views.edit_comment, name="editComment"),
    path('category', views.category_view, name="categoryView"),
    path('category/<str:category_name>', views.category_filter, name="categoryFilter")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from simple_history.models import HistoricalRecords
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(max_length=2048)
    history = HistoricalRecords()
    imageCategory = models.ImageField(upload_to='category_images/', null=True, blank=True)

    def __str__(self):
        return self.name
class Listing(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    winner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='won_listing')
    item = models.CharField(max_length=64)
    description = models.TextField(max_length=2048)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='choose_category')
    starting_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    current_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    url = models.URLField(blank=True, null=True, max_length=500)
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('ended','Ended')
        ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Active')
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

    history = HistoricalRecords()

    def __str__(self):
        return self.item
    def get_bid_count(self):
        return self.bids.count()
    def get_latest_bid(self):
        return self.bids.latest('bid_time')
    

class Bid(models.Model): #Record every bid and take them as one independent data
    object = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='bids')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2,help_text='Enter the what the starting bid should be')
    bid_time = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()

    def __str__(self):
        return f"{self.user.username} bid {self.amount} on {self.object.item} at {self.bid_time}"
    class Meta:
        ordering = ['-bid_time']
    def save(self, *args, **kwargs):
        self.object.current_price = self.amount
        self.object.save()
        super().save(*args, **kwargs)

class Comment(models.Model):
    item = models.ForeignKey(Listing, related_name='comments',  on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=2048)
    comment_time = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()
    
    def __str__(self):
        return f"Comment: {self.content} by {self.user.username} on {self.item.item} at {self.comment_time}"

class Watchlist(models.Model):
    item = models.ForeignKey(Listing, related_name='add_to_watchlist',  on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_tracked = models.BooleanField(default=False)
    history = HistoricalRecords()

    class Meta:
        constraints =[
            models.UniqueConstraint(fields=['item','user'], name='unique_tracked_item')
        ]
    def __str__(self):
        return f"Wathlish: Is {self.item} tracked by {self.user} or not? {self.is_tracked} "

auctions/forms.py
from django import forms
from .models import Listing, Comment, Bid 

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['item','category','description','starting_price','url']
        widgets = {
            'item': forms.TextInput(attrs={'placeholder':'Enter title'}),
            'description': forms.Textarea(attrs={'placeholder':'Enter description'}),
            'starting_price':forms.NumberInput(attrs={'min': 0 }),
            'url':forms.URLInput(attrs={'placeholder':'Enter image URL or Not'}),
        }

class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['amount']
        widgets = {
            'amount':forms.TextInput(attrs={'placeholder':'Bid'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.TextInput(attrs={'placeholder':'Leave your comment'}),
        }

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from .models import User, Listing, Bid, Comment, Watchlist, Category
from .forms import ListingForm, BidForm, CommentForm


def index(request):
    return render(request, "auctions/index.html",{
        "Listings":Listing.objects.all()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")




def add_listing(request):
    if request.method == "POST":
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save(commit=False)
            listing.owner=request.user
            listing.status="active"
            starting_price = int(form.cleaned_data['starting_price'])
            if starting_price <= 0:
                return render(request,"auctions/addListing.html",{
                    "form": form,
                    "message": "the starting price must be greater than 10 dollars! "
                })
            else:
                listing.current_price = starting_price
                listing.save()
                return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/addListing.html",{
                'form': form,
                'message':"Form validation failed. Please check your submit!"
            })
    else:
        form = ListingForm()
        categories = Category.objects.all()
        return render(request, "auctions/addListing.html",{
            'form':form,
            'categories': categories
        })




def get_listing_context(listing_id):
    listing = get_object_or_404(Listing.objects.select_related('category','owner'),id=listing_id)
    context = {
        'listing':listing,
        'bid_times':listing.get_bid_count()
    }
    return listing, context
  
def watch_list(request):
    
        tracked_items = Watchlist.objects.filter(is_tracked=True, user=request.user)

        if tracked_items.exists():
            listings = [ tracked_item.item for tracked_item in tracked_items]
            for listing in listings:
                listing.status = listing.status.upper()
            return render(request, "auctions/watchlist.html",{
                "Listings":listings
            })
        else:
            active_listings = Listing.objects.filter(status='active')
            return render(request, "auctions/watchlist.html",{
                "active_Listings":active_listings
            })

def toggle_watch_list(request, listing_id):
    listing, context = get_listing_context(listing_id)
    if request.method == "POST":
        if Watchlist.objects.filter(item=listing,user=request.user).exists():
            track_item = Watchlist.objects.get(item=listing, user=request.user )
            track_item.is_tracked = not track_item.is_tracked 
            track_item.save()
            print(f"Updated:{track_item}") 
        else: 
            track_item = Watchlist.objects.create(
                item=listing,
                user=request.user,
                is_tracked=True
            )
            print(f"Success: {track_item}")
        return HttpResponseRedirect(reverse("auctions:entryBid", args=(listing_id,)))
    return HttpResponseNotAllowed(['POST'])

def track_status_button(listing, user):
    track_item = Watchlist.objects.filter(item=listing, user=user).first()
    return {
        'track_status': track_item.is_tracked if track_item else False
    }




def add_comment(request, listing_id):
    listing, context = get_listing_context(listing_id)
    if request.method == "POST":
        commentForm = CommentForm(request.POST)
        if commentForm.is_valid():
            comment = commentForm.save(commit=False)
            comment.item = listing
            comment.user = request.user
            comment.save()   
            print(f"Success:{comment}")
            return HttpResponseRedirect(f'{reverse("auctions:entryBid", args=(listing_id,))}?show_comments=all')
    return HttpResponseNotAllowed(['POST'])
       
def edit_comment(request, listing_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id) 
    if request.method == "POST":
        commentForm = CommentForm(request.POST, instance=comment)
        if commentForm.is_valid():
            comment.save()
            return HttpResponseRedirect(f'{reverse("auctions:entryBid", args=(listing_id,))}?show_comments=all')
    else:
        commentForm = commentForm(instance=comment)
        return render(request, "auctions/bidPage.html",{
            'commentForm': commentForm,
            'listing_id': listing_id,
            'comment_id':comment_id
        })
    return HttpResponseNotAllowed(['POST'])

def comment_list(listing):
    comments = Comment.objects.select_related('user').filter(item=listing).order_by('-comment_time')
    comments.count
    return {'Comments':comments}

def edit_comment_view (request):
    edit_comment_id = request.GET.get('edit',None)
    if edit_comment_id:
        return{
            'edit_comment_id':int(edit_comment_id),
            'commentForm': CommentForm(instance=Comment.objects.get(id=int(edit_comment_id)))
        }
    return{
        'edit_comment_id': None,
        'commentForm': CommentForm()
    }

def show_all_comments_view(request):
    return { 'show_all_comments' : request.GET.get('show_comments', None) == 'all'}




def entry_bid(request, listing_id):   
    listing, context = get_listing_context(listing_id)

    if request.user.is_authenticated:
        context.update({
            **edit_comment_view(request),
            **show_all_comments_view(request),
            **track_status_button(listing, request.user),
            **comment_list(listing),
            'now':timezone.now(),
            'message':request.GET.get('message',None),
            'is_owner':request.user == listing.owner,
            'is_winner':request.user == listing.winner,
            'bidForm':BidForm(),
        })
    else: 
        context.update({
            **show_all_comments_view(request),
            **comment_list(listing),
            'commentForm':None,
            'bidForm':None,
            'is_owner': False,
            'is_winner':False,
            'message':request.GET.get('message',None),
        })
    print(context)
    return render(request, "auctions/bidPage.html",context)

def place_bid(request, listing_id):
    listing, context = get_listing_context(listing_id)
    if request.method =="POST":
        bidForm = BidForm(request.POST)
        if bidForm.is_valid():
            bid = bidForm.save(commit=False)
            bid.object = listing
            bid.user = request.user
            amount = int(bidForm.cleaned_data['amount'])
            if amount > listing.current_price + 9:
                bid.save()
                print(f"Bid:{bid}")
                return HttpResponseRedirect(reverse("auctions:entryBid", args=(listing_id,)))
            else:
                context.update({
                  'message': "Your bid must be at least $10 higher than the current price.",
                  'bidForm':bidForm,
                  'now':timezone.now(),
                  **comment_list(listing),
                  **track_status_button(listing, request.user)
                })
                print(context)
                return render(request, "auctions/bidPage.html",context)
        else:
            context.update({
                'message':"Your bid must enter number not words.",
                'bidForm':bidForm,
                'now':timezone.now(),
                **comment_list(listing),
                **track_status_button(listing, request.user)                
            })
            return render(request, "auctions/bidPage.html",context)
    return HttpResponseNotAllowed(['POST'])
          
def end_bid(request, listing_id):
    listing, context = get_listing_context(listing_id)
    if request.method == "POST":  
         try:
            latest_bid=Bid.objects.filter(object=listing).latest('bid_time')
            listing.winner = latest_bid.user
            status="ended"
            listing.status = status
            listing.save()

auctions/templates/auctions/bidPage.html
{% extends "auctions/layout.html" %}

{% block body %}
<div id="bid_card" class="card lg:card-side m-5 p-5 bg-base-100 shadow-xl">
    <div class="rounded-3xl h-auto w-full p-0 lg:mx-3 mb-3 lg:mb-0">
        <img class="w-full max-h-[600px] lg:max-h-full object-cover rounded-3xl"
        src="{% if listing.url %}{{listing.url}}{% else %}/static/placeholder.png{% endif %}" alt="{{listing.item}}">
    </div>

    <div class="card-body p-0 w-full m-0">
        <div class="sticky top-0 z-50 flex flex-col rounded-xl p-0 m-0 shadow-lg bg-base-200">
            <div class="flex justify-center w-full">
                <div class="flex w-1/2 text-nowrap">
                    <div class="m-4 tooltip tooltip-bottom lg:tooltip-right" data-tip="{% if listing.category %} {{listing.category.description}} {% else %} None {% endif %}">
                        <h4 class="badge p-4 badge-outline cursor-pointer font-bold ">{% if listing.category %} {{listing.category.name }} {% else %} Other {% endif %}</h4>
                    </div>
                </div>
                <div class="flex w-1/2 items-center justify-end md:pr-3 space-x-2">
                    <img class="w-8" src="/static/bidding.png" alt="Bid"/>
                    <div class="text-nowrap font-bold">{{bid_times}}</div>
                    {% if user.is_authenticated %}
                    <form action="{% url 'auctions:toggleWatch' listing.id %}#bid_card" method="POST">
                        {% csrf_token %}
                        {% if track_status == False %}
                            <button class="btn shadow-none" type="submit" title="Watch">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                            </svg>
                            </button>
                        {% else %}
                            <button class="btn shadow-none" type="submit" title="Unwatch">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.451 10.451 0 0 1 12 4.5c4.756 0 8.773 3.162 10.065 7.498a10.522 10.522 0 0 1-4.293 5.774M6.228 6.228 3 3m3.228 3.228 3.65 3.65m7.894 7.894L21 21m-3.228-3.228-3.65-3.65m0 0a3 3 0 1 0-4.243-4.243m4.242 4.242L9.88 9.88" />
                            </svg>
                            </button>
                        {% endif %}
                    </form>
                    {% endif %}
                </div>
            </div>
            {% if message %}
            <div class="flex justify-center w-full h-auto m-0 p-2 text-base-200 bg-success bg-opacity-70 rounded-lg ">
                <div>{{ message }}</div>
            </div>
            {% endif %} 
        </div>
        <div class=" z-30 lg:z-0 bg-base-100 flex-grow overflow-y-scroll h-[calc(100vh-150px)]  lg:h-[calc(100vh-80px)] pb-16 p-0" name="card-content">
            <h2 class="flex text-justify text-neutral text-3xl font-bold m-3">{{listing.item}}</h2>
            <div class="flex text-justify text-neutral m-3">{{listing.description}}</div>   
            <div class="stats stats-vertical w-full m-0 mt-5  lg:stats-horizontal overflow-hidden lg:overflow-hidden shadow-lg bg-success bg-opacity-5">
                <div class="stat text-neutral box-border">
                    <div class="stat-title text-center md:text-left">Current price</div>
                    <div class="stat-value text-[25px] text-success text-center md:text-left">$ {{listing.current_price}}</div>
                    <div class="stat-desc text-center md:text-left">Updated: {{listing.updated_time}}</div>
                </div>
                {% if user.is_authenticated %}
                <div class="stat text-neutral box-border">
                    {% if listing.status == 'active' %}
                        {% if is_owner %}
                        <form action="{% url 'auctions:endBid' listing.id %}#bid_card" method="post">
                            {% csrf_token %}
                            <div class="stat-title text-center text-success font-bold"> You are the owner!</div>
                            <div class="stat-actions flex justify-center">
                                <button class="btn btn-success text-white" type="submit"> Close the Bid</button>
                            </div>
                        </form>
                        {% else %}
                        <form action="{% url 'auctions:placeBid' listing.id %}#bid_card" method="post">
                            {% csrf_token %}
                            <div class="stat-title md:text-center text-success font-bold text-[20px]">Place the bid</div>
                            <input type="text" name="amount" 
                            class="input input-bordered w-full placeholder-success font-bold my-4" 
                            placeholder="Bid" 
                            value="{{ bidForm.amount.value|default:''}}" required
                            autofocus
                            />
                        </form>
                        {% endif %}  
                    {% else %}
                    <h2 class="stat-title">Bid ended </h2>
                        {% if is_winner %}
                            <div class="stat-value font-bold text-info">You Won!!</div>
                        {% else %}
                            <div class="stat-value font-bold text-info text-[30px]">Winner is {{listing.winner.username}}</div>
                        {% endif%}
                    {% endif %}
                </div>
                {% endif %}
            </div>  
            {% if user.is_authenticated %} 
            <div class="card flex justify-center m-3" name="card-comments">
                {% include 'auctions/comment.html' %}
            </div>   
            {% endif %}
        </div>

        {% if user.is_authenticated %}
        <div class="sticky z-20 bottom-0 flex justify-center">
            {% if not edit_comment_id %}
                <form class="navbar" action="{% url 'auctions:comment' listing.id %}#bid_card" method="post">
                    {% csrf_token %}
                    <input type="text" name="content" 
                    class="input input-bordered w-full font-bold rounded-2xl "
                    placeholder="Leave your comment here"
                    value="{{ commentForm.content.value|default:''}}" required/>
                </form>
            {% endif %}
        </div>
        {% endif %}

    </div>
</div>
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
    <div class="grid md:grid-cols-3 p-10 gap-5 w-full justify-items-center grid-cols-2">
    {% for Category in Categories %}
        <a class="flex justify-center w-full" href="{% url 'auctions:categoryFilter' Category.name %}">
            <div class="relative w-full max-w-[300px] lg:max-w-[430px] rounded-lg overflow-hidden">
                {% if Category.imageCategory %}
                <img class="rounded-lg h-40 w-full object-top object-cover" src="{{ Category.imageCategory.url }}" alt="{{ Category.name }}">
                {% else %}
                    <p>No image available for this category.</p>
                {% endif %}

                <div class="absolute inset-0 p-10 bg-neutral opacity-45 flex items-center justify-center">
                </div>
                <div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-white font-bold text-lg text-nowrap ">{{Category.name}}</div>
            </div>
        </a>
    {% endfor %}
   </div>


{% endblock %} 

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% include 'auctions/listings.html' %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en" data-theme="light">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale =1">
        <title>{% block title %}Auctions{% endblock %}</title>
        {% tailwind_css %}
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    
    <body class="relative z-0 bg-base text-base-content w-screen">
        <div class="bg-warning absolute z-10  aspect-square top-20 left-14 w-32 h-32 lg:top-36 lg:left-36 lg:w-[700px] lg:h-[700px] rounded-full opacity-90 blur-3xl [transform:translate3d(0,0,0)] "></div>
        <div class="bg-success absolute z-10 aspect-square w-full h-full rounded-full opacity-50 blur-3xl [transform:translate3d(0,0,0)]"></div>
        <div class="bg-info absolute z-10 aspect-square w-1/2 h-full right-14 lg:right-20 rounded-full opacity-50 blur-3xl [transform:translate3d(0,0,0)]"></div>

        <div class="navbar relative z-30 bg-opacity-50 items-center text-base-content w-full shadow-lg rounded-bl-lg rounded-br-lg ">
            <div class="navbar-start w-full h-10 lg:w-1/2 lg:flex relative ">
                <div class="absolute left-0 lg:hidden">
                    {% include 'auctions/nav_menu.html' %}
                </div>
                <h1 class="text-3xl font-bold flex w-full justify-center lg:justify-start lg:pl-5">
                    <a class="w-full text-center lg:text-left" href="{% url 'auctions:index' %}">
                        Auctions
                    </a>
                </h1>
            </div>
            <div class="navbar-center hidden font-bold lg:flex">
                <ul class="menu menu-horizontal px-1 space-x-8">
                        {% if user.is_authenticated %}
                        {% url 'auctions:index' as active_listings_url %}
                        <li><a class="nav_item {% if request.path == active_listings_url %} bg-neutral text-neutral-content transition {% endif %}" 
                            href="{% url 'auctions:index' %}">Active Listings</a></li>

                        {% url 'auctions:newListing' as active_newListing_url %}
                        <li><a class="nav_item {% if request.path == active_newListing_url %} bg-neutral text-neutral-content transition {% endif %}" 
                            href="{% url 'auctions:newListing' %}">Create Listing</a></li>

                        {% url 'auctions:watchList' as active_watchList_url %}
                        <li><a class="nav_item {% if request.path == active_watchList_url %} bg-neutral text-neutral-content transition {% endif %}" 
                            href="{% url 'auctions:watchList' %}">Watch List</a></li>

                        {% url 'auctions:categoryView' as active_categoryView_url %}
                        <li><a class="nav_item {% if request.path == active_categoryView_url %} bg-neutral text-neutral-content transition {% endif %}" 
                            href="{% url 'auctions:categoryView' %}">Category</a></li>

                        {% url 'auctions:logout' as active_logout_url %}
                        <li><a class="nav_item {% if request.path == active_logout_url %} bg-neutral text-neutral-content transition {% endif %}" 
                            href="{% url 'auctions:logout' %}">Log Out</a></li>
                    {% else %}
                        {% url 'auctions:index' as active_listings_url %}
                        <li><a class="nav_item {% if request.path == active_listings_url %} bg-neutral text-neutral-content transition {% endif %}"  
                            href="{% url 'auctions:index' %}">Active Listings</a></li>

                        {% url 'auctions:login' as active_login_url %}
                        <li><a class="nav_item {% if request.path == active_login_url %} bg-neutral text-neutral-content transition {% endif %}" 
                            href="{% url 'auctions:login' %}">Log In</a></li>

                        {% url 'auctions:register' as active_register_url %}
                        <li><a class="nav_item {% if request.path == active_register_url %} bg-neutral text-neutral-content transition {% endif %}" 
                            href="{% url 'auctions:register' %}">Register</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="navbar-end hidden lg:flex pr-5">
                {% if user.is_authenticated %}
                <div class="p-3 mt-1.5">Signed in as <strong class="text-neutral">{{ user.username }}</strong></div>
                {% else %}
                <div class="p-3 mt-1.5">Not signed in.</div>
                {% endif %} 
            </div>
        </div>

        <div class="relative z-20 flex w-full justify-center">
            <main class="w-full mx-auto mt-5 bg-base-100 bg-opacity-70 rounded-lg shadow-lg">
                {% block body %}
                {% endblock %}
            </main>
        </div>
        <footer class="relative z-20 w-full bg-neutral text-neutral-content text-center py-4 mt-8">
            <p>&copy; 2024 Auctions. All rights reserved.</p>
        </footer>
    </body>
</html>

auctions/templates/auctions/nav_menu.html
<div class="py-3">
    <details class=" dropdown dropdown-bottom bg-opacity-0 flex w-[80px]">
        <summary class="btn m-1 bg-opacity-0 border-none shadow-none">
            <svg class="swap-off fill-current bg-opacity-0 " xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 512 512">
                <path d="M64,384H448V341.33H64Zm0-106.67H448V234.67H64ZM64,128v42.67H448V128Z" />
          </svg>
        </summary>
        <ul class="menu dropdown-content bg-base-100 rounded-box z-30 w-52 p-2 shadow">
            {% if user.is_authenticated %}
                <p class="p-3 bg-base-200 rounded-md">Signed in as <strong class="text-neutral">{{ user.username }}</strong></p>
                <li><a class="nav_item" href="{% url 'auctions:index' %}">Active Listings</a></li>
                <li><a class="nav_item" href="{% url 'auctions:logout' %}">Log Out</a></li>
                <li><a class="nav_item" href="{% url 'auctions:newListing' %}">Create Listing</a></li>
                <li><a class="nav_item" href="{% url 'auctions:watchList' %}">Watch List</a></li> 
                <li><a class="nav_item" href="{% url 'auctions:categoryView' %}">Category</a></li>
            {% else %}
                <li><a class="nav_item" href="{% url 'auctions:index' %}">Active Listings</a></li>
                <li><a class="nav_item" href="{% url 'auctions:login' %}">Log In</a></li>
                <li><a class="nav_item" href="{% url 'auctions:register' %}">Register</a></li>
            {% endif %}
        </ul>
    </details>
</div>